In [2]:
import numpy as np

In [3]:
range = 5
X1 = np.linspace(-range, range, num=1 + 2*range, endpoint=True, retstep=True)
X2 = np.linspace(-range, range, num=1 + 2*range, endpoint=True, retstep=True)


In [11]:
Ef, count = 0, 0
for x1 in X1:
    for x2 in X2:
        count += 1
        Ef += x1**2 * x2
        print(count, x1, x2, Ef)


1 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.] [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.] [-125.  -64.  -27.   -8.   -1.    0.    1.    8.   27.   64.  125.]
2 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.] 1.0 [-100.  -48.  -18.   -4.    0.    0.    2.   12.   36.   80.  150.]
3 1.0 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.] [-105.  -52.  -21.   -6.   -1.    0.    3.   14.   39.   84.  155.]
4 1.0 1.0 [-104.  -51.  -20.   -5.    0.    1.    4.   15.   40.   85.  156.]


In [12]:
Ef

array([-104.,  -51.,  -20.,   -5.,    0.,    1.,    4.,   15.,   40.,
         85.,  156.])

In [13]:
X1

(array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]),
 np.float64(1.0))

In [14]:
for x in X1:
    print(x)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
1.0
