In [1]:
import numpy as np


In [32]:
# Generate multi-dimensioned noisy data and add a correlated column.
samples, features = 1000, 5
noise             = np.random.rand(samples, features)
correlator        = np.random.rand(features, 1)
correlations      = np.matmul(noise, correlator)
data              = np.concatenate((noise, correlations), axis=1)

In [33]:
data

array([[0.84310845, 0.51992205, 0.87090434, 0.94827422, 0.47326818,
        0.61700583],
       [0.91239899, 0.9153266 , 0.57404572, 0.91231154, 0.61082135,
        0.6368705 ],
       [0.31477495, 0.66024178, 0.35845138, 0.11668891, 0.96649575,
        0.32614616],
       ...,
       [0.6317714 , 0.81196734, 0.24754461, 0.71676094, 0.41160173,
        0.43223648],
       [0.81509089, 0.42027516, 0.87519168, 0.88477446, 0.31991253,
        0.58814589],
       [0.28817254, 0.077613  , 0.57998102, 0.57603863, 0.54045341,
        0.27272626]])

In [37]:
np.cov(data, rowvar=False)


array([[ 0.08324043,  0.00158702,  0.00323066,  0.00042355,  0.000335  ,
         0.03358193],
       [ 0.00158702,  0.08089204, -0.00096109, -0.00272398,  0.00120943,
         0.01177254],
       [ 0.00323066, -0.00096109,  0.08168719, -0.00308415,  0.00191727,
         0.0195427 ],
       [ 0.00042355, -0.00272398, -0.00308415,  0.0865112 , -0.00047568,
        -0.00059409],
       [ 0.000335  ,  0.00120943,  0.00191727, -0.00047568,  0.08677134,
         0.00335106],
       [ 0.03358193,  0.01177254,  0.0195427 , -0.00059409,  0.00335106,
         0.01930359]])

In [43]:
correlator

array([[0.39189353],
       [0.14019327],
       [0.22482347],
       [0.00380945],
       [0.03020566]])