In [2]:
import numpy as np

In [5]:
theta = 17
orth  = theta + 90

W = np.array([[np.cos(np.deg2rad(theta)), np.sin(np.deg2rad(theta))],[np.cos(np.deg2rad(orth)), np.sin(np.deg2rad(orth))]])


0.29237170472273677

In [6]:
W

array([[ 0.95630476,  0.2923717 ],
       [-0.2923717 ,  0.95630476]])

In [7]:
np.matmul(W, np.transpose(W))

array([[1.00000000e+00, 1.32198639e-16],
       [1.32198639e-16, 1.00000000e+00]])

In [8]:
np.matmul(np.transpose(W), W)

array([[1.00000000e+00, 8.49948194e-17],
       [8.49948194e-17, 1.00000000e+00]])

In [9]:
np.linalg.inv(W)

array([[ 0.95630476, -0.2923717 ],
       [ 0.2923717 ,  0.95630476]])